all:
	./main

str:
	gcc -g -o str str.c -I/opt/python3/include/python3.8 -L/opt/python3/lib -lpython3.8

file:
	gcc -g -o file file.c -I/opt/python3/include/python3.8 -L/opt/python3/lib -lpython3.8

clean:
	rm -rf str file

